In [1]:
%pip install numpy 

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ----------------- ---------------------- 5.5/12.4 MB 14.6 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.4 MB 17.2 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 17.2 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 17.2 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 9.3 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [ ]:
# !pip install numpy -> 옛날방식(잘못된  가상환경에 설치될 위험이 있음)

In [1]:
import numpy as np 

In [2]:
matrix_1 = [
    [1,2],
    [3,4]
]

matrix_2 = [
    [5,6],
    [7,8]
]

matrix_3 = [
    [9,10],
    [11,12]
]

matrix_1 + matrix_2
result = []
for i in range(len(matrix_1)):
    temp = []
    for j in range(len(matrix_1[i])):
        temp.append(matrix_1[i][j] +1)
    result.append(temp)
result

[[2, 3], [4, 5]]

In [3]:
# numpy 숫자 계산 
array_1 = np.array(matrix_1)
array_2 = np.array(matrix_2)
#arr
array_1, type(array_1)

(array([[1, 2],
        [3, 4]]),
 numpy.ndarray)

In [4]:
array_1 + array_2

array([[ 6,  8],
       [10, 12]])

In [5]:
array_1 + 1 # 브로드캐스팅 (차원이 다른 배열끼리의 연산)

array([[2, 3],
       [4, 5]])

In [8]:
# 속도 비교
import time
size = 10000000

# list
x = list(range(size))
y = list(range(size))
start_time= time.time()
z = [x[i]+y[i] for i in range(size)]
print('리스트 걸린시간', time.time() -start_time)
# adlist
x = np.arange(size)
y = np.arange(size)
start_time= time.time()
z = x+y
print('넘파이 걸린시간', time.time() -start_time)

리스트 걸린시간 30.712566614151
넘파이 걸린시간 1.394334316253662


In [10]:
x = np.uint((32,))

In [11]:
x

array([32], dtype=uint64)

In [12]:
x.dtype

dtype('uint64')

In [13]:
x = np.array([1, 2, 3, 4])
print(x.dtype)

int64


In [14]:
x = np.float32([1, 2, 3, 4])
print(x.dtype)

float32


In [15]:
x = np.array([1, 2, 3, 4], dtype=np.float32)
print(x.dtype)

float32


In [16]:
x = np. int32(x)
print(x.dtype)

int32


In [19]:
x = np.array(1)
x

array(1)

In [21]:
x = np.array([1, 2])
print(x.shape) # (2, )
print(x.ndim)
print(x.size)

(2,)
1
2


In [22]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.shape) # (2, 3)
print(x.ndim) # 2
print(x.size) # 6

(2, 3)
2
6


In [23]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
x = np.arange(1, 10, 2)
print(x)

[1 3 5 7 9]


In [25]:
x = np.arange(1, 10, 0.5)
print(x)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [26]:
x = np.arange(10, 1, -0.5)
print(x)

[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


In [27]:
x = np.linspace(1, 20, 5)
print(x)

[ 1.    5.75 10.5  15.25 20.  ]


In [28]:
x = np.linspace(1, 20, 10, endpoint=True)
print(x)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [37]:
x = np.arange(9).reshape(3, 3)
print(x, '\n')
x = np.arange(24).reshape(2, 3, 4)
print(x, '\n')
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x.reshape(2, 3), '\n')
x = np.arange(9).reshape(3, -1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

[[1 2 3]
 [4 5 6]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
x = np.arange(20)
print(x[1:3], '\n')
x = np.arange(20).reshape(4, 5)
print(x, '\n')
print(x[1:3], '\n')
print(x[1:3, 1:3], '\n')
x = np.arange(30).reshape(2, 5, 3)
print(x, '\n')
print(x[:, 3:5, 1])

[1 2] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 6  7]
 [11 12]] 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]] 

[[10 13]
 [25 28]]


In [40]:
x = np.arange(20).reshape(4, 5)
print(x[1][1])
print(x[1, 1])

6
6


In [46]:
x = np.arange(30).reshape((2,5, 3))
x[:, 2:4]

array([[[ 6,  7,  8],
        [ 9, 10, 11]],

       [[21, 22, 23],
        [24, 25, 26]]])

In [ ]:
x[1][2][1] #or x[1,2,1]

np.int64(22)

In [58]:
x= np.arange(20).reshape((4,5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
x[x>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [50]:
np.random.rand(5, 5)

array([[0.29754513, 0.05538376, 0.90776785, 0.88945926, 0.36347888],
       [0.31792807, 0.91921463, 0.14226159, 0.68193568, 0.73730393],
       [0.04342522, 0.49637483, 0.64660644, 0.9012061 , 0.42304877],
       [0.8823955 , 0.20664877, 0.43737179, 0.44302994, 0.86626282],
       [0.32552501, 0.47599252, 0.59396421, 0.51734263, 0.12462875]])

In [51]:
np.random.rand(5, 5)

array([[0.07020331, 0.50149366, 0.85282178, 0.5451508 , 0.06924894],
       [0.17722495, 0.50506498, 0.79941539, 0.55265591, 0.07295882],
       [0.91808753, 0.79074587, 0.07446956, 0.59470476, 0.74894145],
       [0.98257889, 0.66251616, 0.30992335, 0.29153404, 0.35217934],
       [0.20167425, 0.74691882, 0.22560639, 0.26486265, 0.9858606 ]])

In [52]:
np.random.randint(1, 10, size=(5))

array([3, 3, 4, 3, 6], dtype=int32)

In [56]:
print(np.ones([5,5]), '\n') # 모든 값이 1
print(np.zeros([5,5]), '\n') #모든 값이 0
np.eye(5) # 단위행렬 (행렬곱 시 자기 자신이 나오는)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
x = np.arange(1, 4)
y = np.arange(4, 7)

np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [63]:
x = np.arange(10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)
np.concatenate([x, y])
np.concatenate([x, y], axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [64]:
x = np.arange(12)
np.split(x, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [65]:
x = np.arange(16).reshape(4, 4)
np.split(x, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [66]:
x = np.arange(1, 10).reshape(3, 3)
y = np.arange(1, 4)
x + y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [67]:
x = np.array([10, 20, 30]).reshape(3, 1)
y = np.arange(1, 4)
x + y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
### 실습 1
x =np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
y = x*10
y

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [70]:
x = x.reshape(3,3)
y = y.reshape(3,3)

In [71]:
x+y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [72]:
x*y

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [73]:
x@y

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [75]:
### 실습 2

In [80]:
arr = np.linspace(1,20,30)
result =arr +10
result

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

In [76]:
### 실습 3

In [82]:
np.random.seed(5)
x = np.random.randint(1, 101, size=(2,10,10))

new_x = np.where(x>= 50, 1,2)
result = new_x[1,5:, 5:]

result

array([[1, 1, 2, 2, 1],
       [2, 1, 1, 2, 1],
       [1, 2, 1, 1, 1],
       [1, 1, 1, 2, 1],
       [2, 1, 1, 2, 2]])